#Copyright 2016 Matthew Krohn
#
#This file is part of RBATool.
#
#Basic Inventory is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
File generated by Django for new app to render Administrator interface in
admin module
"""

from django.contrib import admin
from .models import Service, Role, Access, Team


class AccessInline(admin.TabularInline):
    """Set up access fields for admin views"""
    model = Access
    extra = 3


class RoleAdmin(admin.ModelAdmin):
    """Edit role name, select membership, show access objects in admin view"""
    search_fields = ['role_name']
    fieldsets = [
        (None,               {'fields': ['role_name']}),
        (None,               {'fields': ['membership']}),
    ]
    inlines = [AccessInline]


class ServiceAdmin(admin.ModelAdmin):
    """Edit server name, show role access levels in admin view"""
    search_fields = ['service_name']
    fieldsets = [
        (None,               {'fields': ['service_name']}),
        (None,               {'fields': ['responsible_team']}),
    ]
    inlines = [AccessInline]

admin.site.register(Role, RoleAdmin)
admin.site.register(Service, ServiceAdmin)
admin.site.register(Team)
