"""File generated by Django for new app"""
from __future__ import unicode_literals

from django.apps import AppConfig


class RbaConfig(AppConfig):
    """Class generated by Django for new app"""
    name = 'rba'
