"""File generated by Django for new app to resolve http requests"""
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<role_id>[0-9]+)/access_results/$', views.access_results,
        name='access_results'),
    url(r'^(?P<service_id>[0-9]+)/service_audit/$', views.service_audit,
        name='service_audit'),
    url(r'^services$', views.service_list, name='service_list'),
]
